# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tender build CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: CI='' npm run build

    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: sonhn98/pte-magic-platform-v2:latest

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 52.221.159.228
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker container stop pte-magic-platform-v2
          sudo docker container rm pte-magic-platform-v2
          sudo docker image rm sonhn98/pte-magic-platform-v2
          sudo docker pull sonhn98/pte-magic-platform-v2
          sudo docker run -d --restart always -p 4000:80/tcp --name pte-magic-platform-v2 sonhn98/pte-magic-platform-v2:latest
